# Generated by Django 3.1.3 on 2023-06-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=40, null=True)),
                ('product_name', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_count', models.IntegerField(blank=True, max_length=10, null=True)),
                ('about_product', models.CharField(blank=True, max_length=500, null=True)),
                ('img_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
